### ISSUE TITLE
3.0.7 gives module not found error

### ISSUE THREAD

**Issue by araker** [tensult/role-acl#3]
Hi, 

First I'd like to mention that I like using this module, the conditionals make it very powerful to deal with fine grained access control. 

After updating to v3.0.7 I get the following error
`
{"column":32,"file":"module.js","function":"Module.load","line":573,"method":"load","native":false}],"stack":["Error: Cannot find module './lib'","    at Function.Module._resolveFilename (module.js:555:15)","    at Function.Module._load (module.js:482:25)","    at Module.require (module.js:604:17)","    at require (internal/module.js:11:18)","    at Object.<anonymous> (/api/node_modules/role-acl/index.js:1:10)","    at Module._compile (module.js:660:30)","    at Object.Module._extensions..js (module.js:671:10)","    at Module.load (module.js:573:32)","    at tryModuleLoad (module.js:513:12)","    at Function.Module._load (module.js:505:3)","    at Module.require (module.js:604:17)","    at require (internal/module.js:11:18)","    at Object.<anonymous> (/api/something.js:6:23)","    at Module._compile (module.js:660:30)","    at Object.Module._extensions..js (module.js:671:10)","    at Module.load (module.js:573:32)"],"level":"error","message":"uncaughtException: Cannot find module './lib'"}`

When looking at the node_modules/role_acl directory the 'lib' directory is missing. It seems that the package is incomplete. Going back to v3.0.6 resolves the error.

**Comment by SherloxFR** [comment]
Same here, great module, but as @araker mentionned, `lib` folder is missing from release 3.0.7
![image](https://user-images.githubusercontent.com/11234273/41726483-8bc2b386-7572-11e8-93ed-39c8d23d6844.png)

**Comment by koladilip** [comment]
I am really sorry @araker @SherloxFR, I have made mistake in publishing to NPM so please don't use v3.0.7 instead please use v3.0.8. Now I have marked v3.0.7 as deprecated also.
